package com.wei.boot.mapper;

import com.wei.boot.model.Area;
import com.wei.boot.model.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int countByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int deleteByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int deleteByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int insert(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int insertSelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    List<Area> selectByExample(AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    Area selectByPrimaryKey(Integer code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int updateByExample(@Param("record") Area record, @Param("example") AreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int updateByPrimaryKeySelective(Area record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_area
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    int updateByPrimaryKey(Area record);
}