package com.wei.boot.mapper;

import com.wei.boot.model.Company;
import com.wei.boot.model.CompanyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int countByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int deleteByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int insert(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int insertSelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    List<Company> selectByExample(CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    Company selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int updateByExampleSelective(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int updateByExample(@Param("record") Company record, @Param("example") CompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int updateByPrimaryKeySelective(Company record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_company
     *
     * @mbggenerated Fri Aug 10 14:34:15 CST 2018
     */
    int updateByPrimaryKey(Company record);
}