package com.wei.boot.mapper;

import com.wei.boot.model.DemoInfo;
import com.wei.boot.model.DemoInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DemoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int countByExample(DemoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int deleteByExample(DemoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int insert(DemoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int insertSelective(DemoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    List<DemoInfo> selectByExample(DemoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    DemoInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") DemoInfo record, @Param("example") DemoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int updateByExample(@Param("record") DemoInfo record, @Param("example") DemoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int updateByPrimaryKeySelective(DemoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demo
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    int updateByPrimaryKey(DemoInfo record);
}