package com.wei.boot.mapper;

import com.wei.boot.model.Dictionary;
import com.wei.boot.model.DictionaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int countByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int deleteByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int insert(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int insertSelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    List<Dictionary> selectByExample(DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    Dictionary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int updateByExample(@Param("record") Dictionary record, @Param("example") DictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int updateByPrimaryKeySelective(Dictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_dictionary
     *
     * @mbggenerated Tue Aug 28 10:26:24 CST 2018
     */
    int updateByPrimaryKey(Dictionary record);
    
    
    List<String> selectAllDicTypes();
}