package com.wei.boot.mapper;

import com.wei.boot.model.RoleMenu;
import com.wei.boot.model.RoleMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int countByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int deleteByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int insertSelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    List<RoleMenu> selectByExample(RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    RoleMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int updateByExample(@Param("record") RoleMenu record, @Param("example") RoleMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int updateByPrimaryKeySelective(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_role_menu
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    int updateByPrimaryKey(RoleMenu record);
    
    /**
     * 批量插入
     * @param list
     */
    void insertBatch(List<RoleMenu> list);
}