package com.wei.boot.mapper;

import com.wei.boot.model.WorkerJobType;
import com.wei.boot.model.WorkerJobTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerJobTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int countByExample(WorkerJobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByExample(WorkerJobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insert(WorkerJobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insertSelective(WorkerJobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    List<WorkerJobType> selectByExample(WorkerJobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    WorkerJobType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkerJobType record, @Param("example") WorkerJobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExample(@Param("record") WorkerJobType record, @Param("example") WorkerJobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKeySelective(WorkerJobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_jobtype
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKey(WorkerJobType record);
}