package com.wei.boot.mapper;

import com.wei.boot.model.WorkerExperience;
import com.wei.boot.model.WorkerExperienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerExperienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int countByExample(WorkerExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByExample(WorkerExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insert(WorkerExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insertSelective(WorkerExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    List<WorkerExperience> selectByExample(WorkerExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    WorkerExperience selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkerExperience record, @Param("example") WorkerExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExample(@Param("record") WorkerExperience record, @Param("example") WorkerExperienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKeySelective(WorkerExperience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_experience
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKey(WorkerExperience record);
}