package com.wei.boot.mapper;

import com.wei.boot.model.WorkerEducation;
import com.wei.boot.model.WorkerEducationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkerEducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int countByExample(WorkerEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByExample(WorkerEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insert(WorkerEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int insertSelective(WorkerEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    List<WorkerEducation> selectByExample(WorkerEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    WorkerEducation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExampleSelective(@Param("record") WorkerEducation record, @Param("example") WorkerEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByExample(@Param("record") WorkerEducation record, @Param("example") WorkerEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKeySelective(WorkerEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx__worker_education
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    int updateByPrimaryKey(WorkerEducation record);
}