package com.wei.boot.model;

import java.util.List;

public class Area {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_area.code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    private Integer code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_area.name
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_area.parent_code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    private Integer parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_area.type
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    private Integer type;
    
    private List<Area> children;

    public List<Area> getChildren() {
		return children;
	}

	public void setChildren(List<Area> children) {
		this.children = children;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_area.code
     *
     * @return the value of t_yx_area.code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_area.code
     *
     * @param code the value for t_yx_area.code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_area.name
     *
     * @return the value of t_yx_area.name
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_area.name
     *
     * @param name the value for t_yx_area.name
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_area.parent_code
     *
     * @return the value of t_yx_area.parent_code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public Integer getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_area.parent_code
     *
     * @param parentCode the value for t_yx_area.parent_code
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public void setParentCode(Integer parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_area.type
     *
     * @return the value of t_yx_area.type
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_area.type
     *
     * @param type the value for t_yx_area.type
     *
     * @mbggenerated Thu Aug 09 16:13:39 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}