package com.wei.boot.model;

import java.util.Date;

public class DemandOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.demand_id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer demandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.order_number
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private String orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.worker_count
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer workerCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.operator_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer operatorUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.customer
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.total_income
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private String totalIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.description
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.create_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.create_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.update_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demand_order.update_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    private Integer updateUser;
    
    
    private String companyName;
    
    private String beginTime;
    
    private String endTime;
    
    private String createUserName;
    
    private Integer confirmState;
    
    private Integer confirmUser;
    
    private Date confirmTime;
    
    private String rejectReason;
    
    private String confirmStateName;
    
    private String confirmUserName;

    public Integer getConfirmState() {
		return confirmState;
	}

	public void setConfirmState(Integer confirmState) {
		this.confirmState = confirmState;
	}

	public Integer getConfirmUser() {
		return confirmUser;
	}

	public void setConfirmUser(Integer confirmUser) {
		this.confirmUser = confirmUser;
	}

	public Date getConfirmTime() {
		return confirmTime;
	}

	public void setConfirmTime(Date confirmTime) {
		this.confirmTime = confirmTime;
	}

	public String getRejectReason() {
		return rejectReason;
	}

	public void setRejectReason(String rejectReason) {
		this.rejectReason = rejectReason;
	}

	public String getConfirmStateName() {
		return confirmStateName;
	}

	public void setConfirmStateName(String confirmStateName) {
		this.confirmStateName = confirmStateName;
	}

	public String getConfirmUserName() {
		return confirmUserName;
	}

	public void setConfirmUserName(String confirmUserName) {
		this.confirmUserName = confirmUserName;
	}

	public String getCreateUserName() {
		return createUserName;
	}

	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	public String getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(String beginTime) {
		this.beginTime = beginTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getCompanyName() {
		return companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.id
     *
     * @return the value of t_yx_demand_order.id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.id
     *
     * @param id the value for t_yx_demand_order.id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.demand_id
     *
     * @return the value of t_yx_demand_order.demand_id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.demand_id
     *
     * @param demandId the value for t_yx_demand_order.demand_id
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setDemandId(Integer demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.order_number
     *
     * @return the value of t_yx_demand_order.order_number
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.order_number
     *
     * @param orderNumber the value for t_yx_demand_order.order_number
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.worker_count
     *
     * @return the value of t_yx_demand_order.worker_count
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getWorkerCount() {
        return workerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.worker_count
     *
     * @param workerCount the value for t_yx_demand_order.worker_count
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setWorkerCount(Integer workerCount) {
        this.workerCount = workerCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.operator_user
     *
     * @return the value of t_yx_demand_order.operator_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getOperatorUser() {
        return operatorUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.operator_user
     *
     * @param operatorUser the value for t_yx_demand_order.operator_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setOperatorUser(Integer operatorUser) {
        this.operatorUser = operatorUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.customer
     *
     * @return the value of t_yx_demand_order.customer
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.customer
     *
     * @param customer the value for t_yx_demand_order.customer
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.total_income
     *
     * @return the value of t_yx_demand_order.total_income
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public String getTotalIncome() {
        return totalIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.total_income
     *
     * @param totalIncome the value for t_yx_demand_order.total_income
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setTotalIncome(String totalIncome) {
        this.totalIncome = totalIncome == null ? null : totalIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.description
     *
     * @return the value of t_yx_demand_order.description
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.description
     *
     * @param description the value for t_yx_demand_order.description
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.create_user
     *
     * @return the value of t_yx_demand_order.create_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.create_user
     *
     * @param createUser the value for t_yx_demand_order.create_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.create_time
     *
     * @return the value of t_yx_demand_order.create_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.create_time
     *
     * @param createTime the value for t_yx_demand_order.create_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.update_time
     *
     * @return the value of t_yx_demand_order.update_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.update_time
     *
     * @param updateTime the value for t_yx_demand_order.update_time
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demand_order.update_user
     *
     * @return the value of t_yx_demand_order.update_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demand_order.update_user
     *
     * @param updateUser the value for t_yx_demand_order.update_user
     *
     * @mbggenerated Sun Oct 21 16:49:38 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}