package com.wei.boot.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DemandExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public DemandExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIsNull() {
            addCriterion("demand_number is null");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIsNotNull() {
            addCriterion("demand_number is not null");
            return (Criteria) this;
        }

        public Criteria andDemandNumberEqualTo(String value) {
            addCriterion("demand_number =", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotEqualTo(String value) {
            addCriterion("demand_number <>", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberGreaterThan(String value) {
            addCriterion("demand_number >", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberGreaterThanOrEqualTo(String value) {
            addCriterion("demand_number >=", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberLessThan(String value) {
            addCriterion("demand_number <", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberLessThanOrEqualTo(String value) {
            addCriterion("demand_number <=", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberLike(String value) {
            addCriterion("demand_number like", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotLike(String value) {
            addCriterion("demand_number not like", value, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberIn(List<String> values) {
            addCriterion("demand_number in", values, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotIn(List<String> values) {
            addCriterion("demand_number not in", values, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberBetween(String value1, String value2) {
            addCriterion("demand_number between", value1, value2, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andDemandNumberNotBetween(String value1, String value2) {
            addCriterion("demand_number not between", value1, value2, "demandNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentIsNull() {
            addCriterion("other_treatment is null");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentIsNotNull() {
            addCriterion("other_treatment is not null");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentEqualTo(String value) {
            addCriterion("other_treatment =", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentNotEqualTo(String value) {
            addCriterion("other_treatment <>", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentGreaterThan(String value) {
            addCriterion("other_treatment >", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentGreaterThanOrEqualTo(String value) {
            addCriterion("other_treatment >=", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentLessThan(String value) {
            addCriterion("other_treatment <", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentLessThanOrEqualTo(String value) {
            addCriterion("other_treatment <=", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentLike(String value) {
            addCriterion("other_treatment like", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentNotLike(String value) {
            addCriterion("other_treatment not like", value, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentIn(List<String> values) {
            addCriterion("other_treatment in", values, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentNotIn(List<String> values) {
            addCriterion("other_treatment not in", values, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentBetween(String value1, String value2) {
            addCriterion("other_treatment between", value1, value2, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andOtherTreatmentNotBetween(String value1, String value2) {
            addCriterion("other_treatment not between", value1, value2, "otherTreatment");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeIsNull() {
            addCriterion("undertake_time is null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeIsNotNull() {
            addCriterion("undertake_time is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeEqualTo(Date value) {
            addCriterion("undertake_time =", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeNotEqualTo(Date value) {
            addCriterion("undertake_time <>", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeGreaterThan(Date value) {
            addCriterion("undertake_time >", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("undertake_time >=", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeLessThan(Date value) {
            addCriterion("undertake_time <", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeLessThanOrEqualTo(Date value) {
            addCriterion("undertake_time <=", value, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeIn(List<Date> values) {
            addCriterion("undertake_time in", values, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeNotIn(List<Date> values) {
            addCriterion("undertake_time not in", values, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeBetween(Date value1, Date value2) {
            addCriterion("undertake_time between", value1, value2, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeTimeNotBetween(Date value1, Date value2) {
            addCriterion("undertake_time not between", value1, value2, "undertakeTime");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserIsNull() {
            addCriterion("undertake_user is null");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserIsNotNull() {
            addCriterion("undertake_user is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserEqualTo(Integer value) {
            addCriterion("undertake_user =", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserNotEqualTo(Integer value) {
            addCriterion("undertake_user <>", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserGreaterThan(Integer value) {
            addCriterion("undertake_user >", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("undertake_user >=", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserLessThan(Integer value) {
            addCriterion("undertake_user <", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserLessThanOrEqualTo(Integer value) {
            addCriterion("undertake_user <=", value, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserIn(List<Integer> values) {
            addCriterion("undertake_user in", values, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserNotIn(List<Integer> values) {
            addCriterion("undertake_user not in", values, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserBetween(Integer value1, Integer value2) {
            addCriterion("undertake_user between", value1, value2, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andUndertakeUserNotBetween(Integer value1, Integer value2) {
            addCriterion("undertake_user not between", value1, value2, "undertakeUser");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIsNull() {
            addCriterion("close_time is null");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIsNotNull() {
            addCriterion("close_time is not null");
            return (Criteria) this;
        }

        public Criteria andCloseTimeEqualTo(Date value) {
            addCriterion("close_time =", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotEqualTo(Date value) {
            addCriterion("close_time <>", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeGreaterThan(Date value) {
            addCriterion("close_time >", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("close_time >=", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeLessThan(Date value) {
            addCriterion("close_time <", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeLessThanOrEqualTo(Date value) {
            addCriterion("close_time <=", value, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeIn(List<Date> values) {
            addCriterion("close_time in", values, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotIn(List<Date> values) {
            addCriterion("close_time not in", values, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeBetween(Date value1, Date value2) {
            addCriterion("close_time between", value1, value2, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseTimeNotBetween(Date value1, Date value2) {
            addCriterion("close_time not between", value1, value2, "closeTime");
            return (Criteria) this;
        }

        public Criteria andCloseStatusIsNull() {
            addCriterion("close_status is null");
            return (Criteria) this;
        }

        public Criteria andCloseStatusIsNotNull() {
            addCriterion("close_status is not null");
            return (Criteria) this;
        }

        public Criteria andCloseStatusEqualTo(Integer value) {
            addCriterion("close_status =", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusNotEqualTo(Integer value) {
            addCriterion("close_status <>", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusGreaterThan(Integer value) {
            addCriterion("close_status >", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("close_status >=", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusLessThan(Integer value) {
            addCriterion("close_status <", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusLessThanOrEqualTo(Integer value) {
            addCriterion("close_status <=", value, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusIn(List<Integer> values) {
            addCriterion("close_status in", values, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusNotIn(List<Integer> values) {
            addCriterion("close_status not in", values, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusBetween(Integer value1, Integer value2) {
            addCriterion("close_status between", value1, value2, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("close_status not between", value1, value2, "closeStatus");
            return (Criteria) this;
        }

        public Criteria andCloseUserIsNull() {
            addCriterion("close_user is null");
            return (Criteria) this;
        }

        public Criteria andCloseUserIsNotNull() {
            addCriterion("close_user is not null");
            return (Criteria) this;
        }

        public Criteria andCloseUserEqualTo(Integer value) {
            addCriterion("close_user =", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserNotEqualTo(Integer value) {
            addCriterion("close_user <>", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserGreaterThan(Integer value) {
            addCriterion("close_user >", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("close_user >=", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserLessThan(Integer value) {
            addCriterion("close_user <", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserLessThanOrEqualTo(Integer value) {
            addCriterion("close_user <=", value, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserIn(List<Integer> values) {
            addCriterion("close_user in", values, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserNotIn(List<Integer> values) {
            addCriterion("close_user not in", values, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserBetween(Integer value1, Integer value2) {
            addCriterion("close_user between", value1, value2, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseUserNotBetween(Integer value1, Integer value2) {
            addCriterion("close_user not between", value1, value2, "closeUser");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIsNull() {
            addCriterion("close_reason is null");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIsNotNull() {
            addCriterion("close_reason is not null");
            return (Criteria) this;
        }

        public Criteria andCloseReasonEqualTo(String value) {
            addCriterion("close_reason =", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotEqualTo(String value) {
            addCriterion("close_reason <>", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonGreaterThan(String value) {
            addCriterion("close_reason >", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonGreaterThanOrEqualTo(String value) {
            addCriterion("close_reason >=", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonLessThan(String value) {
            addCriterion("close_reason <", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonLessThanOrEqualTo(String value) {
            addCriterion("close_reason <=", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonLike(String value) {
            addCriterion("close_reason like", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotLike(String value) {
            addCriterion("close_reason not like", value, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonIn(List<String> values) {
            addCriterion("close_reason in", values, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotIn(List<String> values) {
            addCriterion("close_reason not in", values, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonBetween(String value1, String value2) {
            addCriterion("close_reason between", value1, value2, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCloseReasonNotBetween(String value1, String value2) {
            addCriterion("close_reason not between", value1, value2, "closeReason");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(Integer value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(Integer value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(Integer value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(Integer value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(Integer value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<Integer> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<Integer> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(Integer value1, Integer value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(Integer value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(Integer value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(Integer value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(Integer value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(Integer value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<Integer> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<Integer> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(Integer value1, Integer value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(Integer value1, Integer value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yx_demand
     *
     * @mbggenerated do_not_delete_during_merge Sun Sep 16 21:59:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_yx_demand
     *
     * @mbggenerated Sun Sep 16 21:59:24 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}