package com.wei.boot.model;

public class DemoInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demo.id
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_demo.name
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demo.id
     *
     * @return the value of t_yx_demo.id
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demo.id
     *
     * @param id the value for t_yx_demo.id
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_demo.name
     *
     * @return the value of t_yx_demo.name
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_demo.name
     *
     * @param name the value for t_yx_demo.name
     *
     * @mbggenerated Fri Jul 27 11:39:33 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}