package com.wei.boot.model;

import java.util.Date;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.id
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.type
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.code
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.name
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.sort
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.create_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.create_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.update_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx_dictionary.update_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.id
     *
     * @return the value of t_yx_dictionary.id
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.id
     *
     * @param id the value for t_yx_dictionary.id
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.type
     *
     * @return the value of t_yx_dictionary.type
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.type
     *
     * @param type the value for t_yx_dictionary.type
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.code
     *
     * @return the value of t_yx_dictionary.code
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.code
     *
     * @param code the value for t_yx_dictionary.code
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.name
     *
     * @return the value of t_yx_dictionary.name
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.name
     *
     * @param name the value for t_yx_dictionary.name
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.sort
     *
     * @return the value of t_yx_dictionary.sort
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.sort
     *
     * @param sort the value for t_yx_dictionary.sort
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.create_time
     *
     * @return the value of t_yx_dictionary.create_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.create_time
     *
     * @param createTime the value for t_yx_dictionary.create_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.create_user
     *
     * @return the value of t_yx_dictionary.create_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.create_user
     *
     * @param createUser the value for t_yx_dictionary.create_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.update_time
     *
     * @return the value of t_yx_dictionary.update_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.update_time
     *
     * @param updateTime the value for t_yx_dictionary.update_time
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx_dictionary.update_user
     *
     * @return the value of t_yx_dictionary.update_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx_dictionary.update_user
     *
     * @param updateUser the value for t_yx_dictionary.update_user
     *
     * @mbggenerated Thu Aug 09 14:46:09 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}