package com.wei.boot.model;

import java.util.Date;

public class RoleMenu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.role_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.menu_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.create_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.create_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.update_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_role_menu.update_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    private Integer updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.id
     *
     * @return the value of t_sys_role_menu.id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.id
     *
     * @param id the value for t_sys_role_menu.id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.role_id
     *
     * @return the value of t_sys_role_menu.role_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.role_id
     *
     * @param roleId the value for t_sys_role_menu.role_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.menu_id
     *
     * @return the value of t_sys_role_menu.menu_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.menu_id
     *
     * @param menuId the value for t_sys_role_menu.menu_id
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.create_time
     *
     * @return the value of t_sys_role_menu.create_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.create_time
     *
     * @param createTime the value for t_sys_role_menu.create_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.create_user
     *
     * @return the value of t_sys_role_menu.create_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.create_user
     *
     * @param createUser the value for t_sys_role_menu.create_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.update_time
     *
     * @return the value of t_sys_role_menu.update_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.update_time
     *
     * @param updateTime the value for t_sys_role_menu.update_time
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_role_menu.update_user
     *
     * @return the value of t_sys_role_menu.update_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_role_menu.update_user
     *
     * @param updateUser the value for t_sys_role_menu.update_user
     *
     * @mbggenerated Tue Aug 14 15:16:20 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }
}