package com.wei.boot.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WorkerEducation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.degree
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.school
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.discipline
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String discipline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_education.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Date updateTime;

    
    private String degreeName;
    
    public String getDegreeName() {
		return degreeName;
	}

	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.id
     *
     * @return the value of t_yx__worker_education.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.id
     *
     * @param id the value for t_yx__worker_education.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.worker_id
     *
     * @return the value of t_yx__worker_education.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.worker_id
     *
     * @param workerId the value for t_yx__worker_education.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.degree
     *
     * @return the value of t_yx__worker_education.degree
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.degree
     *
     * @param degree the value for t_yx__worker_education.degree
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.school
     *
     * @return the value of t_yx__worker_education.school
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.school
     *
     * @param school the value for t_yx__worker_education.school
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.description
     *
     * @return the value of t_yx__worker_education.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.description
     *
     * @param description the value for t_yx__worker_education.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.begin_time
     *
     * @return the value of t_yx__worker_education.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.begin_time
     *
     * @param beginTime the value for t_yx__worker_education.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.end_time
     *
     * @return the value of t_yx__worker_education.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.end_time
     *
     * @param endTime the value for t_yx__worker_education.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.discipline
     *
     * @return the value of t_yx__worker_education.discipline
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getDiscipline() {
        return discipline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.discipline
     *
     * @param discipline the value for t_yx__worker_education.discipline
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setDiscipline(String discipline) {
        this.discipline = discipline == null ? null : discipline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.create_user
     *
     * @return the value of t_yx__worker_education.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.create_user
     *
     * @param createUser the value for t_yx__worker_education.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.create_time
     *
     * @return the value of t_yx__worker_education.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.create_time
     *
     * @param createTime the value for t_yx__worker_education.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.update_user
     *
     * @return the value of t_yx__worker_education.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.update_user
     *
     * @param updateUser the value for t_yx__worker_education.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_education.update_time
     *
     * @return the value of t_yx__worker_education.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_education.update_time
     *
     * @param updateTime the value for t_yx__worker_education.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}