package com.wei.boot.model;

public class WorkerJobType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_jobtype.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_jobtype.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_jobtype.first_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer firstId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_jobtype.second_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer secondId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_jobtype.id
     *
     * @return the value of t_yx__worker_jobtype.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_jobtype.id
     *
     * @param id the value for t_yx__worker_jobtype.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_jobtype.worker_id
     *
     * @return the value of t_yx__worker_jobtype.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_jobtype.worker_id
     *
     * @param workerId the value for t_yx__worker_jobtype.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_jobtype.first_id
     *
     * @return the value of t_yx__worker_jobtype.first_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getFirstId() {
        return firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_jobtype.first_id
     *
     * @param firstId the value for t_yx__worker_jobtype.first_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setFirstId(Integer firstId) {
        this.firstId = firstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_jobtype.second_id
     *
     * @return the value of t_yx__worker_jobtype.second_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getSecondId() {
        return secondId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_jobtype.second_id
     *
     * @param secondId the value for t_yx__worker_jobtype.second_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setSecondId(Integer secondId) {
        this.secondId = secondId;
    }
}