package com.wei.boot.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WorkerExperience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.company
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.position
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.industry
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.salary
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_yx__worker_experience.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.id
     *
     * @return the value of t_yx__worker_experience.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.id
     *
     * @param id the value for t_yx__worker_experience.id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.worker_id
     *
     * @return the value of t_yx__worker_experience.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.worker_id
     *
     * @param workerId the value for t_yx__worker_experience.worker_id
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.company
     *
     * @return the value of t_yx__worker_experience.company
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.company
     *
     * @param company the value for t_yx__worker_experience.company
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.position
     *
     * @return the value of t_yx__worker_experience.position
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.position
     *
     * @param position the value for t_yx__worker_experience.position
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.industry
     *
     * @return the value of t_yx__worker_experience.industry
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.industry
     *
     * @param industry the value for t_yx__worker_experience.industry
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.salary
     *
     * @return the value of t_yx__worker_experience.salary
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.salary
     *
     * @param salary the value for t_yx__worker_experience.salary
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.begin_time
     *
     * @return the value of t_yx__worker_experience.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.begin_time
     *
     * @param beginTime the value for t_yx__worker_experience.begin_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.end_time
     *
     * @return the value of t_yx__worker_experience.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.end_time
     *
     * @param endTime the value for t_yx__worker_experience.end_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.description
     *
     * @return the value of t_yx__worker_experience.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.description
     *
     * @param description the value for t_yx__worker_experience.description
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.create_user
     *
     * @return the value of t_yx__worker_experience.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.create_user
     *
     * @param createUser the value for t_yx__worker_experience.create_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.create_time
     *
     * @return the value of t_yx__worker_experience.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.create_time
     *
     * @param createTime the value for t_yx__worker_experience.create_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.update_user
     *
     * @return the value of t_yx__worker_experience.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.update_user
     *
     * @param updateUser the value for t_yx__worker_experience.update_user
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_yx__worker_experience.update_time
     *
     * @return the value of t_yx__worker_experience.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_yx__worker_experience.update_time
     *
     * @param updateTime the value for t_yx__worker_experience.update_time
     *
     * @mbggenerated Thu Aug 30 11:23:45 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}